function [spl, ...
          ndim_spl, ...
          dim_spl, ...
          steps_spl, ...
          discret_spl, ...
          dims_left] = ...
                     get_split_information(splits, ...
                                           ndims_run, ...
                                           dims_run, ...
                                           steps_run, ...
                                           discrets_run, ...
                                           dims_left_run, ...
                                           i)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

spl = splits{i};
ndim_spl = ndims_run{i};
dim_spl = dims_run{i};
steps_spl = steps_run{i};
discret_spl = discrets_run{i};
dims_left = dims_left_run{i};
% n_corners = n_corners_run{i};

end

